version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: fd
      POSTGRES_PASSWORD: fd
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./food-delivery-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food_delivery
      SPRING_DATASOURCE_USERNAME: fd
      SPRING_DATASOURCE_PASSWORD: fd
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./food-delivery-frontend
    environment:
      REACT_APP_API_BASE_URL: http://4.232.137.90:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: